version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 7493:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: rel

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080